#!/usr/bin/env bash

package=$1
# Unlink any previous version
command -- "$DOTFILES_ROOT/libexec/dotfiles--unlink-package" "$package"

export DOTFILES_PACKAGE_SRC="$DOTFILES_ROOT/packages/$package"
if [ ! -e "$DOTFILES_PACKAGE_SRC/install" ]; then
    echo "Package $package does not exist"
    exit 1
fi

pushd $DOTFILES_PACKAGE_SRC >/dev/null
export DOTFILES_PACKAGE=$package
command -- "$DOTFILES_ROOT/libexec/dotfiles--install-wrapper" "./install"
popd >/dev/null
