#!/usr/bin/env bash

# Usage: Install dotfile packages

if [ "$#" = "0" ]; then
    echo "usage:"
    echo "  $DOTFILES_CMD install -l"
    echo "  $DOTFILES_CMD install <package> ..."
    exit
fi

packages=""
list=false

while [ ! "$#" = "0" ]; do
    case "$1" in
    -l)
        list=true ;;
    *)
        packages="$1 $packages" ;;
    esac
    shift
done

packages=$(echo -n $packages)

if $list; then
    pushd "$DOTFILES_ROOT/packages"
    for f in *; do
        [ -e "$f/install" ] && echo "  $f"
    done
    popd
    exit
fi

for p in $packages; do
    package_root="$DOTFILES_ROOT/packages/$p"
    if [ ! -e "$package_root/install" ]; then
        echo "Package $p does not exist"
        exit 1
    fi
    pushd $package_root
    command -- "$DOTFILES_ROOT/libexec/dotfiles--install-wrapper" "./install"
    popd
done
