#!/usr/bin/env bash

register_link() {
    local l="$1"
    local linkfile="$DOTFILES_ROOT/.data/$DOTFILES_PACKAGE.links"
    touch "$linkfile"
    grep -Fxq "$l" "$linkfile" || echo "$l" >> "$linkfile"
}

simple_install() {
    local src="$1"
    local dst="$2"
    local src_path="$DOTFILES_PACKAGE_SRC/$src"
    local dst_path="$HOME/$dst"
    local dst_dir=$(dirname "$dst_path")

    [ ! -e "$dst_dir" ] && mkdir -p "$dst_dir"

    rm -rf "$dst_path"
    ln -s "$src_path" "$dst_path"
    register_link "$dst_path"
}

source -- "$1"
