#!/usr/bin/env bash

# Usage: Install dotfile packages

if [ "$#" = "0" ]; then
    echo "usage:"
    echo "  $DOTFILES_CMD install -l"
    echo "  $DOTFILES_CMD install -L"
    echo "  $DOTFILES_CMD install -a"
    echo "  $DOTFILES_CMD install <package> ..."
    exit
fi

packages=()
list=false
list_installed=false
all=false

shopt -s nullglob

while [ ! "$#" = "0" ]; do
    case "$1" in
    -l|--list)
        list=true ;;
    -L|--installed)
        list_installed=true ;;
    -a|--all)
        all=true ;;
    *)
        packages+=("$1") ;;
    esac
    shift
done

if $list && $list_installed; then
    echo "error: can't use -l along with -L"
    exit 1
fi

if $list_installed; then
    pushd "$DOTFILES_DATA" >/dev/null
    for f in *.links; do
        echo "  ${f%%.*}"
    done
    popd >/dev/null
    exit
fi

if $list; then
    pushd "$DOTFILES_ROOT/packages" >/dev/null
    for f in *; do
        [ -e "$f/install" ] && echo "  $f"
    done
    popd >/dev/null
    exit
fi

if $all; then
    packages=()
    echo "Installing every package"
    pushd "$DOTFILES_ROOT/packages" >/dev/null
    for f in *; do
        [ -e "$f/install" ] && packages+=("$f")
    done
    popd >/dev/null
fi

for p in ${packages[@]}; do
    echo "Installing package $p"
    command -- "$DOTFILES_ROOT/libexec/dotfiles--install-package" "$p"
done
