#!/usr/bin/env bash

shopt -s nullglob

exec_cmd() {
    local cmd="$1"
    local path="$DOTFILES_ROOT/libexec/dotfiles-$cmd"
    if [ -e "$path" ]; then
        shift
        command -- "$path" "$@"
    else
        echo "dotfiles: command not found: $cmd"
        exit 1
    fi
}

export DOTFILES_CMD="$0"
export DOTFILES_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export DOTFILES_DATA="$DOTFILES_ROOT/.data"

mkdir -p "$DOTFILES_DATA"

if [ "$#" = "0" ]; then
    exec_cmd "help"
else
    exec_cmd "$@"
fi
