#!/usr/bin/env bash

# Usage: Uninstall dotfiles

if [ ! "$#" = "1" ]; then
    echo "dotfiles: usage: $DOTFILES_CMD uninstall <package>"
    exit 1
fi

package="$1"
package_root="$DOTFILES_ROOT/dotfiles/$package"

if [ ! -e "$package_root" ]; then
    echo "Package not installed: $package"
    exit 1
fi

command -- "$DOTFILES_ROOT/libexec/dotfiles--unlink-package" "$package"
rm -rf "$package_root"
