#!/usr/bin/env bash

package=$1
# Unlink any previous version
command -- "$DOTFILES_ROOT/libexec/dotfiles--unlink-package" "$package"

package_root="$DOTFILES_ROOT/packages/$package"
if [ ! -e "$package_root/install" ] && [ ! -e "$DOTFILES_ROOT/dotfiles/$package" ]; then
    echo "Package $package does not exist"
    exit 1
fi

pushd $package_root >/dev/null
export DOTFILES_PACKAGE_ROOT="$DOTFILES_ROOT/dotfiles/$package"
mkdir -p "$DOTFILES_PACKAGE_ROOT"
command -- "$DOTFILES_ROOT/libexec/dotfiles--install-wrapper" "./install"
popd >/dev/null
