#!/usr/bin/env bash

# Usage: Install dotfile packages

if [ "$#" = "0" ]; then
    echo "usage:"
    echo "  $DOTFILES_CMD install -l"
    echo "  $DOTFILES_CMD install -L"
    echo "  $DOTFILES_CMD install <package> ..."
    exit
fi

packages=""
list=false
list_installed=false

while [ ! "$#" = "0" ]; do
    case "$1" in
    -l)
        list=true ;;
    -L)
        list_installed=true ;;
    *)
        packages="$1 $packages" ;;
    esac
    shift
done

packages=$(echo -n $packages)

if $list && $list_installed; then
    echo "error: can't use -l along with -L"
    exit 1
fi

if $list_installed; then
    pushd "$DOTFILES_ROOT/dotfiles"
    for f in *; do
        echo "  $f"
    done
    popd
    exit
fi

if $list; then
    pushd "$DOTFILES_ROOT/packages"
    for f in *; do
        [ -e "$f/install" ] && echo "  $f"
    done
    popd
    exit
fi

for p in $packages; do
    command -- "$DOTFILES_ROOT/libexec/dotfiles--install-package" "$p"
done
