#!/usr/bin/env bash

# Usage: Updates dotfiles and installed packages

shopt -s nullglob

cd "$DOTFILES_ROOT"
git pull -f >/dev/null

cd "$DOTFILES_DATA"
for p in *.links; do
    command -- "$DOTFILES_ROOT/libexec/dotfiles--install-package" "${p%%.*}"
done
