#!/usr/bin/env bash

# Usage: Uninstall dotfiles

if [ ! "$#" = "1" ]; then
    echo "dotfiles: usage: $DOTFILES_CMD uninstall <package>"
    exit 1
fi

package="$1"
if [ ! command -- "$DOTFILES_ROOT/libexec/dotfiles--unlink-package" "$package" ]; then
    echo "error: package '$package' does not exist."
    exit 1
fi
