setopt APPEND_HISTORY
setopt AUTOCD
setopt AUTO_LIST
setopt EXTENDED_HISTORY
setopt GLOB_DOTS
setopt HASH_LIST_ALL
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt NULLGLOB
setopt PROMPT_SUBST
setopt PUSHD_SILENT
setopt SHARE_HISTORY
setopt RM_STAR_SILENT
setopt NO_BGNICE
setopt NO_BEEP

HISTFILE="$HOME/.cache/zsh/history"
HISTSIZE=10000
SAVEHIST=10000

bindkey -e
